# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyRadio_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(492, 194)
        MainWindow.setMinimumSize(QtCore.QSize(492, 194))
        MainWindow.setMaximumSize(QtCore.QSize(492, 194))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.combo_list_radio = QtWidgets.QComboBox(self.centralwidget)
        self.combo_list_radio.setGeometry(QtCore.QRect(10, 60, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.combo_list_radio.setFont(font)
        self.combo_list_radio.setObjectName("combo_list_radio")
        self.Button_Play = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Play.setGeometry(QtCore.QRect(10, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_Play.setFont(font)
        self.Button_Play.setObjectName("Button_Play")
        self.Button_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Stop.setGeometry(QtCore.QRect(250, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_Stop.setFont(font)
        self.Button_Stop.setObjectName("Button_Stop")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 471, 51))
        self.groupBox.setObjectName("groupBox")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 20, 451, 22))
        self.horizontalSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider.setMinimum(-60)
        self.horizontalSlider.setMaximum(-1)
        self.horizontalSlider.setPageStep(5)
        self.horizontalSlider.setProperty("value", -30)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.groupBox.raise_()
        self.combo_list_radio.raise_()
        self.Button_Play.raise_()
        self.Button_Stop.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 492, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_Play.setText(_translate("MainWindow", "Слушать"))
        self.Button_Stop.setText(_translate("MainWindow", "Остановить"))
        self.groupBox.setTitle(_translate("MainWindow", "Регулировка громкости"))
